using System.Data;using Microsoft.Data.SqlClient;using PizzaSatinAlmaYonetimi.Web.Data;using PizzaSatinAlmaYonetimi.Web.Models;
namespace PizzaSatinAlmaYonetimi.Web.Services;
public sealed class AyarlarService(ISqlConnectionFactory factory,ISifreDogrulamaService sifreService):IAyarlarService
{
 public async Task<ProfilModel>ProfilGetirAsync(int uid,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_KullaniciDetayiGetir");cmd.Parameters.Add("@KullaniciID",SqlDbType.Int).Value=uid;await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))throw new InvalidOperationException("Kullanıcı bulunamadı.");return new(){AdSoyad=r.GetString("AdSoyad"),Eposta=r.GetString("Eposta"),KullaniciAdi=r.GetString("KullaniciAdi"),RolAdi=r.GetString("RolAdi")};}
 public async Task ProfilGuncelleAsync(int uid,ProfilModel m,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_KendiProfiliniGuncelle");cmd.Parameters.Add("@KullaniciID",SqlDbType.Int).Value=uid;cmd.Parameters.Add("@AdSoyad",SqlDbType.NVarChar,150).Value=m.AdSoyad;cmd.Parameters.Add("@Eposta",SqlDbType.NVarChar,150).Value=m.Eposta;await cmd.ExecuteNonQueryAsync(ct);}
 public async Task SifreGuncelleAsync(int uid,string kullaniciAdi,SifreDegistirModel m,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using(var giris=Komut(c,"dbo.sp_GirisKullanicisiniGetir")){giris.Parameters.Add("@KullaniciAdi",SqlDbType.NVarChar,100).Value=kullaniciAdi;await using var r=await giris.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct)||r.GetInt32("KullaniciID")!=uid||!sifreService.Dogrula(m.MevcutSifre,(byte[])r["SifreSalt"],(byte[])r["SifreHash"]))throw new InvalidOperationException("Mevcut şifre hatalı.");}var(hash,salt)=sifreService.HashOlustur(m.YeniSifre);await using var cmd=Komut(c,"dbo.sp_SifreGuncelle");cmd.Parameters.Add("@KullaniciID",SqlDbType.Int).Value=uid;cmd.Parameters.Add("@YeniSifreHash",SqlDbType.VarBinary).Value=hash;cmd.Parameters.Add("@YeniSifreSalt",SqlDbType.VarBinary).Value=salt;await cmd.ExecuteNonQueryAsync(ct);}
 private static SqlCommand Komut(SqlConnection c,string a)=>new(a,c){CommandType=CommandType.StoredProcedure};
}
