using System.Data;using Microsoft.Data.SqlClient;using PizzaSatinAlmaYonetimi.Web.Data;using PizzaSatinAlmaYonetimi.Web.Models;
namespace PizzaSatinAlmaYonetimi.Web.Services;
public sealed class SatinAlmaTalebiService(ISqlConnectionFactory factory,ILogger<SatinAlmaTalebiService> logger):ISatinAlmaTalebiService
{
 public async Task<IReadOnlyList<TalepListeSatiri>>ListeleAsync(TalepFiltreModel? f,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);var filtreli=f is not null&&(!string.IsNullOrWhiteSpace(f.AramaMetni)||!string.IsNullOrWhiteSpace(f.TalepEden)||!string.IsNullOrWhiteSpace(f.Durumlar)||f.BaslangicTarihi.HasValue||f.BitisTarihi.HasValue);await using var cmd=Komut(c,filtreli?"dbo.sp_TalepleriFiltrele":"dbo.sp_TalepleriListele");if(filtreli){P(cmd,"@AramaMetni",SqlDbType.NVarChar,f!.AramaMetni,150);P(cmd,"@TalepEden",SqlDbType.NVarChar,f.TalepEden,150);P(cmd,"@Durumlar",SqlDbType.NVarChar,f.Durumlar,20);P(cmd,"@BaslangicTarihi",SqlDbType.Date,f.BaslangicTarihi);P(cmd,"@BitisTarihi",SqlDbType.Date,f.BitisTarihi);P(cmd,"@MinMiktar",SqlDbType.Decimal,null);P(cmd,"@MaxMiktar",SqlDbType.Decimal,null);}var list=new List<TalepListeSatiri>();await using(var r=await cmd.ExecuteReaderAsync(ct)){while(await r.ReadAsync(ct))list.Add(new(r.GetInt32("TalepID"),r.GetString("TalepNo"),r.GetString("UrunAdi"),r.GetDecimal(r.GetOrdinal("Miktar")),r.GetString("Birim"),r.GetString("TalepEden"),r.GetDateTime("TalepTarihi"),r.IsDBNull("Aciklama")?null:r.GetString("Aciklama"),r.GetString("Durum")));}await using var sahiplik=new SqlCommand("SELECT TalepID, TalepEdenKullaniciID FROM dbo.SatinAlmaTalepleri",c);await using var sr=await sahiplik.ExecuteReaderAsync(ct);var sahipler=new Dictionary<int,int>();while(await sr.ReadAsync(ct))sahipler[sr.GetInt32(0)]=sr.GetInt32(1);return list.Select(x=>x with{TalepEdenKullaniciId=sahipler.GetValueOrDefault(x.TalepId)}).ToList();}
 public async Task<TalepFormModel?>DetayGetirAsync(string no,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TalepDetayiGetir");P(cmd,"@TalepNo",SqlDbType.NVarChar,no,20);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);return await r.ReadAsync(ct)?new(){TalepId=r.GetInt32("TalepID"),TalepNo=r.GetString("TalepNo"),TalepEden=r.GetString("TalepEden"),UrunAdi=r.GetString("UrunAdi"),Miktar=r.GetDecimal(r.GetOrdinal("Miktar")),Birim=r.GetString("Birim"),Aciklama=r.IsDBNull("Aciklama")?null:r.GetString("Aciklama")}:null;}
 public async Task<bool>KullaniciyaAitMiAsync(int talepId,int kullaniciId,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=new SqlCommand("SELECT COUNT(1) FROM dbo.SatinAlmaTalepleri WHERE TalepID=@TalepID AND TalepEdenKullaniciID=@KullaniciID",c);P(cmd,"@TalepID",SqlDbType.Int,talepId);P(cmd,"@KullaniciID",SqlDbType.Int,kullaniciId);return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct))==1;}
 public async Task EkleAsync(int uid,TalepFormModel m,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TalepEkle");P(cmd,"@TalepEdenKullaniciID",SqlDbType.Int,uid);Alanlar(cmd,m,false);await cmd.ExecuteNonQueryAsync(ct);try{await YeniTalepBildirAsync(c,uid,m,ct);}catch(Exception ex){logger.LogError(ex,"Yeni talep bildirimi oluşturulamadı. Kullanıcı: {KullaniciID}",uid);}}
 public async Task GuncelleAsync(TalepFormModel m,CancellationToken ct){if(!m.TalepId.HasValue)throw new InvalidOperationException("Talep ID zorunludur.");await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TalepDuzenle");P(cmd,"@TalepID",SqlDbType.Int,m.TalepId);Alanlar(cmd,m,true);await cmd.ExecuteNonQueryAsync(ct);}
 public async Task ReddetAsync(string no,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TalebiReddet");P(cmd,"@TalepNo",SqlDbType.NVarChar,no,20);await cmd.ExecuteNonQueryAsync(ct);}
 public async Task GeriAlAsync(string talepNo,CancellationToken ct)
 {
  await using var c=factory.CreateConnection();
  await c.OpenAsync(ct);
  await using var cmd=Komut(c,"dbo.sp_TalepGeriAl");
  P(cmd,"@TalepNo",SqlDbType.NVarChar,talepNo,20);
  await cmd.ExecuteNonQueryAsync(ct);
 }
 private static async Task YeniTalepBildirAsync(SqlConnection c,int uid,TalepFormModel m,CancellationToken ct){await using var detay=new SqlCommand("SELECT TOP(1) CONCAT(sat.TalepNo,N' numaralı yeni satın alma talebi oluşturuldu. Ürün: ',sat.UrunAdi,N'. Talep Eden: ',k.AdSoyad,N'. Talep Tarihi: ',CONVERT(nvarchar(10),sat.TalepTarihi,104),N'.') FROM dbo.SatinAlmaTalepleri sat INNER JOIN dbo.Kullanicilar k ON k.KullaniciID=sat.TalepEdenKullaniciID WHERE sat.TalepEdenKullaniciID=@KullaniciID ORDER BY sat.TalepID DESC",c);P(detay,"@KullaniciID",SqlDbType.Int,uid);var mesaj=Convert.ToString(await detay.ExecuteScalarAsync(ct));if(string.IsNullOrWhiteSpace(mesaj))return;await using var bildirim=new SqlCommand("INSERT dbo.Bildirimler(KullaniciID,Baslik,Mesaj,OkunduMu,OlusturmaTarihi,OkunmaTarihi) SELECT k.KullaniciID,N'Yeni Satın Alma Talebi',@Mesaj,0,GETDATE(),NULL FROM dbo.Kullanicilar k INNER JOIN dbo.Roller r ON r.RolID=k.RolID WHERE k.Durum=1 AND r.RolAdi=N'Satın Alma Uzmanı' AND EXISTS(SELECT 1 FROM dbo.Kullanicilar x INNER JOIN dbo.Roller xr ON xr.RolID=x.RolID WHERE x.KullaniciID=@KullaniciID AND xr.RolAdi=N'Talep Oluşturan Kullanıcı') AND NOT EXISTS(SELECT 1 FROM dbo.Bildirimler b WHERE b.KullaniciID=k.KullaniciID AND b.Baslik=N'Yeni Satın Alma Talebi' AND b.Mesaj=@Mesaj)",c);P(bildirim,"@KullaniciID",SqlDbType.Int,uid);P(bildirim,"@Mesaj",SqlDbType.NVarChar,mesaj,500);await bildirim.ExecuteNonQueryAsync(ct);}
 private static void Alanlar(SqlCommand c,TalepFormModel m,bool duzenle){P(c,"@UrunAdi",SqlDbType.NVarChar,m.UrunAdi,150);P(c,duzenle?"@UrunAciklamasi":"@Aciklama",SqlDbType.NVarChar,m.Aciklama,duzenle?255:500);P(c,"@Miktar",SqlDbType.Decimal,m.Miktar);c.Parameters["@Miktar"].Precision=18;c.Parameters["@Miktar"].Scale=2;P(c,"@Birim",SqlDbType.NVarChar,m.Birim,duzenle?20:30);}
 private static SqlCommand Komut(SqlConnection c,string ad)=>new(ad,c){CommandType=CommandType.StoredProcedure};private static void P(SqlCommand c,string ad,SqlDbType tip,object? deger,int? boyut=null){var p=boyut.HasValue?c.Parameters.Add(ad,tip,boyut.Value):c.Parameters.Add(ad,tip);p.Value=deger??DBNull.Value;}
}
