using System.Data;using Microsoft.Data.SqlClient;using PizzaSatinAlmaYonetimi.Web.Data;using PizzaSatinAlmaYonetimi.Web.Models;
namespace PizzaSatinAlmaYonetimi.Web.Services;
public sealed class SatinAlmaOnayService(ISqlConnectionFactory factory,ILogger<SatinAlmaOnayService> logger):ISatinAlmaOnayService
{
 public async Task<IReadOnlyList<OnayBekleyenTeklif>>ListeleAsync(CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_OnayBekleyenTeklifleriListele");await using var r=await cmd.ExecuteReaderAsync(ct);var l=new List<OnayBekleyenTeklif>();while(await r.ReadAsync(ct))l.Add(new(r.GetInt32("TeklifID"),r.GetString("TeklifNo"),r.GetString("TalepNo"),r.GetString("UrunAdi"),r.GetString("TalepEden"),r.GetString("FirmaAdi"),r.GetDecimal(r.GetOrdinal("TeklifTutari")),r.GetString("ParaBirimi"),r.GetInt32("TeslimSuresiGun"),r.GetDateTime("TeklifTarihi"),r.IsDBNull("GecerlilikTarihi")?null:r.GetDateTime("GecerlilikTarihi")));return l;}
 public async Task SiparisOlusturAsync(int teklifId,int uid,CancellationToken ct){var bekleyen=await ListeleAsync(ct);var teklif=bekleyen.FirstOrDefault(x=>x.TeklifId==teklifId)??throw new InvalidOperationException("Sipariş oluşturulabilecek seçilmiş teklif bulunamadı.");await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using(var cmd=Komut(c,"dbo.sp_SiparisOlustur")){cmd.Parameters.Add("@TeklifID",SqlDbType.Int).Value=teklifId;cmd.Parameters.Add("@OnaylayanKullaniciID",SqlDbType.Int).Value=uid;await cmd.ExecuteNonQueryAsync(ct);}var olustu=false;await using(var kontrol=Komut(c,"dbo.sp_SiparisleriListele")){await using var r=await kontrol.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))if(r.GetString("TeklifNo")==teklif.TeklifNo){olustu=true;break;}}if(!olustu)throw new InvalidOperationException("Sipariş oluşturulamadı.");try{await SiparisBildirAsync(c,teklifId,ct);}catch(Exception ex){logger.LogError(ex,"Sipariş bildirimi oluşturulamadı. Teklif ID: {TeklifID}",teklifId);}}
 private static async Task SiparisBildirAsync(SqlConnection c,int teklifId,CancellationToken ct){await using var cmd=new SqlCommand("DECLARE @Mesaj nvarchar(500); SELECT @Mesaj=CONCAT(s.SiparisNo,N' numaralı satın alma siparişi oluşturuldu. Talep: ',sat.TalepNo,N'. Teklif: ',t.TeklifNo,N'. Ürün: ',sat.UrunAdi,N'. Tedarikçi: ',f.FirmaAdi,N'. Tutar: ',FORMAT(t.TeklifTutari,N'N2',N'tr-TR'),N' ',RTRIM(t.ParaBirimi),N'.') FROM dbo.SatinAlmaSiparisleri s INNER JOIN dbo.Teklifler t ON t.TeklifID=s.TeklifID INNER JOIN dbo.SatinAlmaTalepleri sat ON sat.TalepID=s.TalepID INNER JOIN dbo.Tedarikciler ted ON ted.TedarikciID=t.TedarikciID INNER JOIN dbo.Firmalar f ON f.FirmaID=ted.FirmaID WHERE s.TeklifID=@TeklifID; INSERT dbo.Bildirimler(KullaniciID,Baslik,Mesaj,OkunduMu,OlusturmaTarihi,OkunmaTarihi) SELECT k.KullaniciID,N'Sipariş Oluşturuldu',@Mesaj,0,GETDATE(),NULL FROM dbo.Kullanicilar k INNER JOIN dbo.Roller r ON r.RolID=k.RolID INNER JOIN dbo.SatinAlmaSiparisleri s ON s.TeklifID=@TeklifID INNER JOIN dbo.SatinAlmaTalepleri sat ON sat.TalepID=s.TalepID WHERE @Mesaj IS NOT NULL AND k.Durum=1 AND (r.RolAdi=N'Satın Alma Yöneticisi' OR k.KullaniciID=sat.TalepEdenKullaniciID) AND NOT EXISTS(SELECT 1 FROM dbo.Bildirimler b WHERE b.KullaniciID=k.KullaniciID AND b.Baslik=N'Sipariş Oluşturuldu' AND b.Mesaj=@Mesaj)",c);cmd.Parameters.Add("@TeklifID",SqlDbType.Int).Value=teklifId;await cmd.ExecuteNonQueryAsync(ct);}
 private static SqlCommand Komut(SqlConnection c,string a)=>new(a,c){CommandType=CommandType.StoredProcedure};
}
