using System.Data;using Microsoft.Data.SqlClient;using PizzaSatinAlmaYonetimi.Web.Data;using PizzaSatinAlmaYonetimi.Web.Models;
namespace PizzaSatinAlmaYonetimi.Web.Services;
public sealed class TedarikciYonetimiService(ISqlConnectionFactory factory):ITedarikciYonetimiService
{
 public async Task<IReadOnlyList<TedarikciListeSatiri>>ListeleAsync(TedarikciFiltreModel? f,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);var filtreli=f is not null&&(!string.IsNullOrWhiteSpace(f.AramaMetni)||f.Durum.HasValue||f.BaslangicTarihi.HasValue||f.BitisTarihi.HasValue);await using var cmd=Komut(c,filtreli?"dbo.sp_TedarikcileriFiltrele":"dbo.sp_TedarikcileriListele");if(filtreli){P(cmd,"@AramaMetni",SqlDbType.NVarChar,f!.AramaMetni,150);P(cmd,"@Durum",SqlDbType.Int,f.Durum);P(cmd,"@BaslangicTarihi",SqlDbType.Date,f.BaslangicTarihi);P(cmd,"@BitisTarihi",SqlDbType.Date,f.BitisTarihi);}await using var r=await cmd.ExecuteReaderAsync(ct);var list=new List<TedarikciListeSatiri>();while(await r.ReadAsync(ct))list.Add(new(r.GetInt32("TedarikciID"),r.GetString("FirmaAdi"),r.GetString("VergiNo"),r.IsDBNull("Telefon")?null:r.GetString("Telefon"),r.IsDBNull("Eposta")?null:r.GetString("Eposta"),r.IsDBNull("Adres")?null:r.GetString("Adres"),r.GetString("Durum"),r.GetDateTime("KayitTarihi")));return list;}
 public async Task<TedarikciFormModel?>DetayGetirAsync(int id,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TedarikciDetayiGetir");P(cmd,"@TedarikciID",SqlDbType.Int,id);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);return await r.ReadAsync(ct)?new(){TedarikciId=r.GetInt32("TedarikciID"),FirmaAdi=r.GetString("FirmaAdi"),VergiNo=r.GetString("VergiNo"),Telefon=r.IsDBNull("Telefon")?null:r.GetString("Telefon"),Eposta=r.IsDBNull("Eposta")?null:r.GetString("Eposta"),Adres=r.IsDBNull("Adres")?null:r.GetString("Adres")}:null;}
 public async Task EkleAsync(TedarikciFormModel m,CancellationToken ct)=>await Calistir("dbo.sp_TedarikciEkle",m,ct);
 public async Task GuncelleAsync(TedarikciFormModel m,CancellationToken ct){if(!m.TedarikciId.HasValue)throw new InvalidOperationException("Tedarikçi ID zorunludur.");await Calistir("dbo.sp_TedarikciGuncelle",m,ct);}
 public async Task DurumGuncelleAsync(int id,int durum,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TedarikciDurumuGuncelle");P(cmd,"@TedarikciID",SqlDbType.Int,id);P(cmd,"@YeniDurum",SqlDbType.Int,durum);await cmd.ExecuteNonQueryAsync(ct);}
 private async Task Calistir(string ad,TedarikciFormModel m,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,ad);if(m.TedarikciId.HasValue)P(cmd,"@TedarikciID",SqlDbType.Int,m.TedarikciId);P(cmd,"@FirmaAdi",SqlDbType.NVarChar,m.FirmaAdi,150);P(cmd,"@VergiNo",SqlDbType.NVarChar,m.VergiNo,20);P(cmd,"@Telefon",SqlDbType.NVarChar,m.Telefon,30);P(cmd,"@Adres",SqlDbType.NVarChar,m.Adres,500);P(cmd,"@Eposta",SqlDbType.NVarChar,m.Eposta,150);await cmd.ExecuteNonQueryAsync(ct);}
 private static SqlCommand Komut(SqlConnection c,string ad)=>new(ad,c){CommandType=CommandType.StoredProcedure};private static void P(SqlCommand c,string ad,SqlDbType tip,object? deger,int? boyut=null){var p=boyut.HasValue?c.Parameters.Add(ad,tip,boyut.Value):c.Parameters.Add(ad,tip);p.Value=deger??DBNull.Value;}
}
