using System.Data;using Microsoft.Data.SqlClient;using PizzaSatinAlmaYonetimi.Web.Data;using PizzaSatinAlmaYonetimi.Web.Models;
namespace PizzaSatinAlmaYonetimi.Web.Services;
public sealed class TeklifGirisiService(ISqlConnectionFactory factory):ITeklifGirisiService
{
 public async Task<IReadOnlyList<TeklifListeSatiri>>ListeleAsync(TeklifFiltreModel? f,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);var filtreli=f is not null&&(!string.IsNullOrWhiteSpace(f.AramaMetni)||!string.IsNullOrWhiteSpace(f.FirmaAdi)||!string.IsNullOrWhiteSpace(f.Durumlar)||f.BaslangicTarihi.HasValue||f.BitisTarihi.HasValue||f.MinTutar.HasValue||f.MaxTutar.HasValue);await using var cmd=Komut(c,filtreli?"dbo.sp_TeklifleriFiltrele":"dbo.sp_TeklifleriListele");if(filtreli){P(cmd,"@AramaMetni",SqlDbType.NVarChar,f!.AramaMetni,150);P(cmd,"@FirmaAdi",SqlDbType.NVarChar,f.FirmaAdi,150);P(cmd,"@Durumlar",SqlDbType.NVarChar,f.Durumlar,20);P(cmd,"@BaslangicTarihi",SqlDbType.Date,f.BaslangicTarihi);P(cmd,"@BitisTarihi",SqlDbType.Date,f.BitisTarihi);P(cmd,"@MinTutar",SqlDbType.Decimal,f.MinTutar);P(cmd,"@MaxTutar",SqlDbType.Decimal,f.MaxTutar);}await using var r=await cmd.ExecuteReaderAsync(ct);var ham=new List<TeklifListeSatiri>();while(await r.ReadAsync(ct))ham.Add(new(r.GetInt32("TeklifID"),r.GetString("TeklifNo"),r.GetString("TalepNo"),r.GetString("UrunAdi"),null,r.GetString("FirmaAdi"),null,r.GetDecimal(r.GetOrdinal("TeklifTutari")),r.GetString("ParaBirimi"),r.GetInt32("TeslimSuresiGun"),KolonVar(r,"SKT")&&!r.IsDBNull("SKT")?r.GetDateTime("SKT"):null,r.GetDateTime("TeklifTarihi"),r.IsDBNull("GecerlilikTarihi")?null:r.GetDateTime("GecerlilikTarihi"),Durum(r.GetString("Durum"))));await r.CloseAsync();var sonuc=new List<TeklifListeSatiri>();foreach(var x in ham){var d=await DetayGetirAsync(x.TeklifNo,ct);sonuc.Add(x with{Aciklama=d?.Aciklama,BirimFiyat=d?.BirimFiyat,Skt=d?.Skt??x.Skt});}return sonuc;}
 public async Task<TeklifFormModel?>DetayGetirAsync(string no,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TeklifDetayiGetir");P(cmd,"@TeklifNo",SqlDbType.NVarChar,no,20);await using var r=await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow,ct);if(!await r.ReadAsync(ct))return null;return new(){TeklifId=r.GetInt32("TeklifID"),TeklifNo=r.GetString("TeklifNo"),TalepNo=r.GetString("TalepNo"),UrunAdi=r.GetString("UrunAdi"),FirmaAdi=r.GetString("FirmaAdi"),Tutar=r.GetDecimal(r.GetOrdinal("TeklifTutari")),TeslimSuresiGun=r.GetInt32("TeslimSuresiGun"),Skt=r.IsDBNull("SKT")?null:r.GetDateTime("SKT"),TeklifTarihi=r.GetDateTime("TeklifTarihi"),GecerlilikTarihi=r.IsDBNull("GecerlilikTarihi")?null:r.GetDateTime("GecerlilikTarihi"),ParaBirimi=r.GetString("ParaBirimi"),Durum=Durum(r.GetString("Durum")),TedarikciId=null,BirimFiyat=r.IsDBNull("BirimFiyat")?null:r.GetDecimal(r.GetOrdinal("BirimFiyat")),Aciklama=r.IsDBNull("KalemAciklamasi")?null:r.GetString("KalemAciklamasi")};}
 public async Task<IReadOnlyList<TeklifTalepSecenegi>>TalepleriGetirAsync(CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TalepleriListele");await using var r=await cmd.ExecuteReaderAsync(ct);var l=new List<TeklifTalepSecenegi>();while(await r.ReadAsync(ct))l.Add(new(r.GetString("TalepNo"),r.GetString("UrunAdi")));return l;}
 public async Task<IReadOnlyList<TeklifTedarikciSecenegi>>TedarikcileriGetirAsync(CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TedarikcileriListele");await using var r=await cmd.ExecuteReaderAsync(ct);var l=new List<TeklifTedarikciSecenegi>();while(await r.ReadAsync(ct))if(r.GetString("Durum")=="Aktif")l.Add(new(r.GetInt32("TedarikciID"),r.GetString("FirmaAdi")));return l;}
 public async Task EkleAsync(int uid,TeklifFormModel m,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TeklifEkle");P(cmd,"@TalepNo",SqlDbType.NVarChar,m.TalepNo,20);P(cmd,"@FirmaAdi",SqlDbType.NVarChar,m.FirmaAdi,150);P(cmd,"@TeklifGirenKullaniciID",SqlDbType.Int,uid);P(cmd,"@BirimFiyat",SqlDbType.Decimal,m.Tutar);P(cmd,"@TeslimSuresiGun",SqlDbType.Int,m.TeslimSuresiGun);TarihPara(cmd,m);await cmd.ExecuteNonQueryAsync(ct);}
 public async Task GuncelleAsync(TeklifFormModel m,CancellationToken ct){if(!m.TeklifId.HasValue||!m.TedarikciId.HasValue)throw new InvalidOperationException("Teklif ve tedarikçi seçimi zorunludur.");await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TeklifGuncelle");P(cmd,"@TeklifID",SqlDbType.Int,m.TeklifId);P(cmd,"@TedarikciID",SqlDbType.Int,m.TedarikciId);P(cmd,"@TeklifTutari",SqlDbType.Decimal,m.Tutar);P(cmd,"@TeslimSuresiGun",SqlDbType.Int,m.TeslimSuresiGun);TarihPara(cmd,m);await cmd.ExecuteNonQueryAsync(ct);}
 public async Task SilAsync(int id,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TeklifSil");P(cmd,"@TeklifID",SqlDbType.Int,id);await cmd.ExecuteNonQueryAsync(ct);}
 private static void TarihPara(SqlCommand c,TeklifFormModel m){P(c,"@SKT",SqlDbType.Date,m.Skt);P(c,"@GecerlilikTarihi",SqlDbType.Date,m.GecerlilikTarihi);P(c,"@ParaBirimi",SqlDbType.Char,m.ParaBirimi.ToUpperInvariant(),3);}private static string Durum(string d)=>d=="İnceleniyor"?"Girildi":d;private static bool KolonVar(SqlDataReader r,string n){for(var i=0;i<r.FieldCount;i++)if(r.GetName(i)==n)return true;return false;}private static SqlCommand Komut(SqlConnection c,string a)=>new(a,c){CommandType=CommandType.StoredProcedure};private static void P(SqlCommand c,string a,SqlDbType t,object? d,int? b=null){var p=b.HasValue?c.Parameters.Add(a,t,b.Value):c.Parameters.Add(a,t);p.Value=d??DBNull.Value;if(t==SqlDbType.Decimal){p.Precision=18;p.Scale=2;}}
}
