using System.Data;using Microsoft.Data.SqlClient;using PizzaSatinAlmaYonetimi.Web.Data;using PizzaSatinAlmaYonetimi.Web.Models;
namespace PizzaSatinAlmaYonetimi.Web.Services;
public sealed class TeklifKarsilastirmaService(ISqlConnectionFactory factory):ITeklifKarsilastirmaService
{
 public async Task<IReadOnlyList<KarsilastirmaTeklifi>>ListeleAsync(string no,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,"dbo.sp_TalebeAitTeklifleriListele");P(cmd,"@TalepNo",no);await using var r=await cmd.ExecuteReaderAsync(ct);var l=new List<KarsilastirmaTeklifi>();while(await r.ReadAsync(ct))l.Add(new(r.GetString("TeklifNo"),r.GetString("TalepNo"),r.GetString("UrunAdi"),r.GetString("TalepEden"),r.GetString("FirmaAdi"),r.GetDecimal(r.GetOrdinal("TeklifTutari")),r.GetString("ParaBirimi"),r.GetInt32("TeslimSuresiGun"),r.IsDBNull("SKT")?null:r.GetDateTime("SKT"),r.IsDBNull("GecerlilikTarihi")?null:r.GetDateTime("GecerlilikTarihi"),r.GetString("Durum")=="İnceleniyor"?"Girildi":r.GetString("Durum")));return l;}
 public Task SecAsync(string no,CancellationToken ct)=>Calistir("dbo.sp_TeklifSec",no,ct);public Task ReddetAsync(string no,CancellationToken ct)=>Calistir("dbo.sp_TeklifiReddet",no,ct);
 public Task SecimiGeriAlAsync(string no,CancellationToken ct)=>GeriAl(no,1,true,ct);
 public Task ReddetmeyiGeriAlAsync(string no,CancellationToken ct)=>GeriAl(no,2,false,ct);
 private async Task GeriAl(string no,int beklenenDurum,bool siparisKontrolu,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{if(siparisKontrolu){await using var siparis=new SqlCommand("SELECT COUNT(1) FROM dbo.SatinAlmaSiparisleri S INNER JOIN dbo.Teklifler T ON T.TeklifID=S.TeklifID WHERE T.TeklifNo=@TeklifNo",c,tx);P(siparis,"@TeklifNo",no);if(Convert.ToInt32(await siparis.ExecuteScalarAsync(ct))>0)throw new InvalidOperationException("Sipariş oluşturulmuş bir teklifin seçimi geri alınamaz.");}await using var guncelle=new SqlCommand("UPDATE dbo.Teklifler SET TeklifDurumID=0 WHERE TeklifNo=@TeklifNo AND TeklifDurumID=@BeklenenDurum; IF @@ROWCOUNT=0 SELECT CAST(NULL AS INT) ELSE SELECT TalepID FROM dbo.Teklifler WHERE TeklifNo=@TeklifNo",c,tx);P(guncelle,"@TeklifNo",no);guncelle.Parameters.Add("@BeklenenDurum",SqlDbType.Int).Value=beklenenDurum;var talepId=await guncelle.ExecuteScalarAsync(ct);if(talepId is null||talepId is DBNull)throw new InvalidOperationException("Teklif durumu geri alma işlemi için uygun değil.");await using var talep=new SqlCommand("UPDATE dbo.SatinAlmaTalepleri SET TalepDurumID=CASE WHEN EXISTS(SELECT 1 FROM dbo.Teklifler WHERE TalepID=@TalepID AND TeklifDurumID=1) THEN 2 ELSE 1 END WHERE TalepID=@TalepID",c,tx);talep.Parameters.Add("@TalepID",SqlDbType.Int).Value=talepId;await talep.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);}catch{await tx.RollbackAsync(ct);throw;}}
 private async Task Calistir(string ad,string no,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=Komut(c,ad);P(cmd,"@TeklifNo",no);await cmd.ExecuteNonQueryAsync(ct);}private static SqlCommand Komut(SqlConnection c,string a)=>new(a,c){CommandType=CommandType.StoredProcedure};private static void P(SqlCommand c,string a,string d)=>c.Parameters.Add(a,SqlDbType.NVarChar,20).Value=d;
}
