using System.Data;
using Microsoft.Data.SqlClient;
using PizzaSatinAlmaYonetimi.Web.Data;
using PizzaSatinAlmaYonetimi.Web.Models;
namespace PizzaSatinAlmaYonetimi.Web.Services;
public sealed class TeslimatTakibiService(ISqlConnectionFactory factory):ITeslimatTakibiService
{
 private const string Sql="""SELECT S.SiparisID,S.SiparisNo,T.TalepNo,T.UrunAdi,F.FirmaAdi Tedarikci,T.Miktar,T.Birim,DATEADD(DAY,TF.TeslimSuresiGun,S.SiparisTarihi) BeklenenTeslimTarihi,TK.GercekTeslimTarihi,TK.TeslimEdilenMiktar,TK.KusurluMiktar,CASE WHEN TK.TeslimatID IS NOT NULL THEN N'Tamamlandı' WHEN CAST(DATEADD(DAY,TF.TeslimSuresiGun,S.SiparisTarihi) AS date)<CAST(GETDATE() AS date) THEN N'Gecikmiş' ELSE N'Bekleniyor' END Durum FROM dbo.SatinAlmaSiparisleri S INNER JOIN dbo.SatinAlmaTalepleri T ON T.TalepID=S.TalepID INNER JOIN dbo.Teklifler TF ON TF.TeklifID=S.TeklifID INNER JOIN dbo.Tedarikciler TD ON TD.TedarikciID=TF.TedarikciID INNER JOIN dbo.Firmalar F ON F.FirmaID=TD.FirmaID LEFT JOIN dbo.TeslimatKayitlari TK ON TK.SiparisID=S.SiparisID WHERE S.SiparisDurumID<>2 AND (@Arama IS NULL OR S.SiparisNo LIKE N'%'+@Arama+N'%' OR T.TalepNo LIKE N'%'+@Arama+N'%' OR T.UrunAdi LIKE N'%'+@Arama+N'%') ORDER BY CASE WHEN TK.TeslimatID IS NULL THEN 0 ELSE 1 END,DATEADD(DAY,TF.TeslimSuresiGun,S.SiparisTarihi),S.SiparisID DESC;""";
 public async Task<IReadOnlyList<TeslimatSatiri>>ListeleAsync(string? arama,string? durum,CancellationToken ct){await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var cmd=new SqlCommand(Sql,c);cmd.Parameters.Add("@Arama",SqlDbType.NVarChar,100).Value=string.IsNullOrWhiteSpace(arama)?DBNull.Value:arama.Trim();await using var r=await cmd.ExecuteReaderAsync(ct);var l=new List<TeslimatSatiri>();while(await r.ReadAsync(ct)){var x=Oku(r);if(string.IsNullOrWhiteSpace(durum)||x.Durum==durum)l.Add(x);}return l;}
 public async Task<TeslimatSatiri?>DetayAsync(int id,CancellationToken ct)=>(await ListeleAsync(null,null,ct)).FirstOrDefault(x=>x.SiparisId==id);
 public async Task KaydetAsync(TeslimatKayitModel m,int uid,CancellationToken ct){var s=await DetayAsync(m.SiparisId,ct)??throw new InvalidOperationException("Sipariş bulunamadı.");if(s.Durum=="Tamamlandı")throw new InvalidOperationException("Bu siparişin teslimatı daha önce kaydedilmiş.");var teslim=m.TeslimEdilenMiktar!.Value;var kusurlu=m.KusurluMiktar!.Value;if(kusurlu>teslim)throw new InvalidOperationException("Kusurlu miktar teslim edilen miktardan büyük olamaz.");if(teslim>s.SiparisMiktari)throw new InvalidOperationException("Teslim edilen miktar sipariş miktarından büyük olamaz.");await using var c=factory.CreateConnection();await c.OpenAsync(ct);await using var tx=(SqlTransaction)await c.BeginTransactionAsync(ct);await using var cmd=new SqlCommand("INSERT dbo.TeslimatKayitlari(SiparisID,GercekTeslimTarihi,TeslimEdilenMiktar,KusurluMiktar,KaydedenKullaniciID)VALUES(@id,@t,@m,@k,@u);UPDATE dbo.SatinAlmaSiparisleri SET SiparisDurumID=1 WHERE SiparisID=@id;",c,tx);cmd.Parameters.Add("@id",SqlDbType.Int).Value=m.SiparisId;cmd.Parameters.Add("@t",SqlDbType.Date).Value=m.GercekTeslimTarihi!.Value.Date;var p=cmd.Parameters.Add("@m",SqlDbType.Decimal);p.Precision=18;p.Scale=2;p.Value=teslim;var q=cmd.Parameters.Add("@k",SqlDbType.Decimal);q.Precision=18;q.Scale=2;q.Value=kusurlu;cmd.Parameters.Add("@u",SqlDbType.Int).Value=uid;await cmd.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);}
 private static TeslimatSatiri Oku(SqlDataReader r)=>new(r.GetInt32("SiparisID"),r.GetString("SiparisNo"),r.GetString("TalepNo"),r.GetString("UrunAdi"),r.GetString("Tedarikci"),r.GetDecimal(r.GetOrdinal("Miktar")),r.GetString("Birim"),r.GetDateTime("BeklenenTeslimTarihi"),r.GetString("Durum"),r.IsDBNull("GercekTeslimTarihi")?null:r.GetDateTime("GercekTeslimTarihi"),r.IsDBNull("TeslimEdilenMiktar")?null:r.GetDecimal(r.GetOrdinal("TeslimEdilenMiktar")),r.IsDBNull("KusurluMiktar")?null:r.GetDecimal(r.GetOrdinal("KusurluMiktar")));
}
