using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using PizzaSatinAlmaYonetimi.Web.Models;using PizzaSatinAlmaYonetimi.Web.Services;
namespace PizzaSatinAlmaYonetimi.Web.Controllers;
[Authorize(Roles="Satın Alma Yöneticisi,Satın Alma Uzmanı,Talep Oluşturan Kullanıcı")]
public sealed class SatinAlmaTalepleriController(ISatinAlmaTalebiService service,ILogger<SatinAlmaTalepleriController> logger):Controller
{
 [HttpGet]public async Task<IActionResult>Index([FromQuery]TalepFiltreModel filtre,string? panel,string? duzenleNo,CancellationToken ct){var kullaniciId=int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);var talepOlusturan=User.IsInRole("Talep Oluşturan Kullanıcı");var form=!string.IsNullOrWhiteSpace(duzenleNo)?await service.DetayGetirAsync(duzenleNo,ct)??new():new TalepFormModel();if(talepOlusturan&&form.TalepId.HasValue&&!await service.KullaniciyaAitMiAsync(form.TalepId.Value,kullaniciId,ct))return Forbid();return View(new SatinAlmaTalepleriViewModel{Talepler=await service.ListeleAsync(filtre,ct),Filtre=filtre,Form=form,AcikPanel=panel,GirisYapanKullaniciId=kullaniciId});}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult>Ekle(TalepFormModel form,CancellationToken ct){if(!ModelState.IsValid)return await Hatali(form,"ekle",ct);var id=int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);return await Islem(()=>service.EkleAsync(id,form,ct),"Satın alma talebi oluşturuldu.","Talep oluşturulamadı.");}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult>Guncelle(TalepFormModel form,CancellationToken ct){if(!ModelState.IsValid)return await Hatali(form,"duzenle",ct);if(string.IsNullOrWhiteSpace(form.TalepNo))return BadRequest();var kayit=await service.DetayGetirAsync(form.TalepNo,ct);if(kayit is null||kayit.TalepId!=form.TalepId)return BadRequest();var kullaniciId=int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);if(User.IsInRole("Talep Oluşturan Kullanıcı")&&!await service.KullaniciyaAitMiAsync(kayit.TalepId!.Value,kullaniciId,ct))return Forbid();return await Islem(()=>service.GuncelleAsync(form,ct),"Talep bilgileri güncellendi.","Talep güncellenemedi.");}
 [HttpPost][ValidateAntiForgeryToken][Authorize(Roles="Satın Alma Yöneticisi")]public async Task<IActionResult>Reddet(string talepNo,CancellationToken ct)=>await Islem(()=>service.ReddetAsync(talepNo,ct),"Talep reddedildi.","Talep reddedilemedi.");
 [HttpPost][ValidateAntiForgeryToken][Authorize(Roles="Satın Alma Yöneticisi")]public async Task<IActionResult>GeriAl(string talepNo,CancellationToken ct)=>await Islem(()=>service.GeriAlAsync(talepNo,ct),"Talep geri alındı.","Talep geri alınamadı.");
 private async Task<IActionResult>Hatali(TalepFormModel form,string panel,CancellationToken ct)=>View("Index",new SatinAlmaTalepleriViewModel{Talepler=await service.ListeleAsync(null,ct),Form=form,AcikPanel=panel,GirisYapanKullaniciId=int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!)});
 private async Task<IActionResult>Islem(Func<Task>a,string b,string h){try{await a();TempData["Basari"]=b;}catch(Exception ex){logger.LogError(ex,h);TempData["Hata"]=h+" Bilgileri kontrol ederek yeniden deneyin.";}return RedirectToAction(nameof(Index));}
}
