using System.Security.Claims;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using PizzaSatinAlmaYonetimi.Web.Models;using PizzaSatinAlmaYonetimi.Web.Services;
namespace PizzaSatinAlmaYonetimi.Web.Controllers;
[Authorize(Roles="Satın Alma Yöneticisi,Satın Alma Uzmanı")]
public sealed class TeklifGirisiController(ITeklifGirisiService service,ILogger<TeklifGirisiController> logger):Controller
{
 [HttpGet]public async Task<IActionResult>Index([FromQuery]TeklifFiltreModel filtre,string? panel,string? duzenleNo,CancellationToken ct){var tedarikciler=await service.TedarikcileriGetirAsync(ct);var form=!string.IsNullOrWhiteSpace(duzenleNo)?await service.DetayGetirAsync(duzenleNo,ct)??new():new TeklifFormModel();if(form.TeklifId.HasValue){form.TedarikciId=tedarikciler.FirstOrDefault(x=>x.FirmaAdi==form.FirmaAdi)?.TedarikciId;if(form.Durum!="Girildi")panel=null;}return View(await Model(filtre,form,panel,tedarikciler,ct));}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult>Ekle(TeklifFormModel form,CancellationToken ct){if(!ModelState.IsValid)return View("Index",await Model(new(),form,"ekle",null,ct));var id=int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);return await Islem(()=>service.EkleAsync(id,form,ct),"Teklif başarıyla kaydedildi.","Teklif kaydedilemedi.");}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult>Guncelle(TeklifFormModel form,CancellationToken ct){ModelState.Remove(nameof(form.FirmaAdi));if(!form.TedarikciId.HasValue)ModelState.AddModelError(nameof(form.TedarikciId),"Tedarikçi seçimi zorunludur.");if(!ModelState.IsValid)return View("Index",await Model(new(),form,"duzenle",null,ct));if(string.IsNullOrWhiteSpace(form.TeklifNo))return BadRequest();var kayit=await service.DetayGetirAsync(form.TeklifNo,ct);if(kayit is null||kayit.TeklifId!=form.TeklifId||kayit.Durum!="Girildi")return BadRequest();return await Islem(()=>service.GuncelleAsync(form,ct),"Teklif bilgileri güncellendi.","Teklif güncellenemedi.");}
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult>Sil(int teklifId,CancellationToken ct)=>await Islem(()=>service.SilAsync(teklifId,ct),"Teklif silindi.","Teklif silinemedi.");
 private async Task<TeklifGirisiViewModel>Model(TeklifFiltreModel f,TeklifFormModel form,string? panel,IReadOnlyList<TeklifTedarikciSecenegi>? ts,CancellationToken ct)=>new(){Teklifler=await service.ListeleAsync(f,ct),Talepler=await service.TalepleriGetirAsync(ct),Tedarikciler=ts??await service.TedarikcileriGetirAsync(ct),Filtre=f,Form=form,AcikPanel=panel};
 private async Task<IActionResult>Islem(Func<Task>a,string b,string h){try{await a();TempData["Basari"]=b;}catch(Exception ex){logger.LogError(ex,h);TempData["Hata"]=h+" İşlem kurallarını kontrol ederek yeniden deneyin.";}return RedirectToAction(nameof(Index));}
}
